name: tailscale

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Tailscale version to use.'
        required: true
        default: '1.18.2'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Download Tailscale
        shell: bash
        id: download
        env:
          VERSION: ${{ inputs.version }}
        run: |
          set -ex
          MINOR=$(echo "$VERSION" | awk -F '.' {'print $2'})
          URL="https://pkgs.tailscale.com/stable/tailscale_${VERSION}_amd64.tgz"
          curl "$URL" -o tailscale.tgz
          tar -C /tmp -xzf tailscale.tgz
          rm tailscale.tgz
          TSPATH=/tmp/tailscale_${VERSION}_amd64
          sudo mv "${TSPATH}/tailscale" "${TSPATH}/tailscaled" /usr/bin

      - name: Run Tailscale
        shell: bash
        env:
          TAILSCALE_AUTHKEY: ${{ secrets.TAILSCALE_AUTHKEY }}
        run: |
          set- ex
          sudo tailscaled 2>~/tailscaled.log &
          HOSTNAME="ec2-3-145-137-241.us-east-2.compute.amazonaws.com"
          sudo tailscale up --authkey ${TAILSCALE_AUTHKEY} --hostname=${HOSTNAME} 

      - name: check for
        run:
          tailscale status | grep -q hello